// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	broker "hello-world/producer/broker"

	mock "github.com/stretchr/testify/mock"
)

// AmqpDial is an autogenerated mock type for the AmqpDial type
type AmqpDial struct {
	mock.Mock
}

// Execute provides a mock function with given fields: url
func (_m *AmqpDial) Execute(url string) (broker.AmqpConnection, error) {
	ret := _m.Called(url)

	var r0 broker.AmqpConnection
	if rf, ok := ret.Get(0).(func(string) broker.AmqpConnection); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broker.AmqpConnection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
