name: rabbitMQ Hello world test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Linters
        run: cd .\rabbitMQ\'hello world'\ && go vet ./... && cd ../../

      - name: Test
        run: cd .\rabbitMQ\'hello world'\ && go test -v ./... && cd ../../

      
